import pandas as pd
import subprocess
import os

class VitELOWrapper:
    def __init__(self, julia_path="julia", script_path="vitelo.jl"):
        self.julia_path = julia_path
        self.script_path = script_path
        self.temp_input = "temp_matches_for_julia.csv"
        self.temp_output = "VitELO.csv" # We will tell Julia to save as CSV

    def prepare_data(self, df):
        """
        Converts the main pipeline DataFrame into the format vitelo.jl expects.
        Expected columns in Julia: rd, rf, bd, bf, s_red, s_blue, date
        """
        # Mapping your existing DataFrame columns to Julia names
        # Adjust these strings to match your actual results.xlsx column names
        julia_df = df[[
            'red_defender', 'red_forward', 
            'blue_defender', 'blue_forward', 
            'result_red', 'result_blue', 'date'
        ]].copy()
        
        julia_df.columns = ['rd', 'rf', 'bd', 'bf', 's_red', 's_blue', 'date']
        
        # Ensure date is string format for Julia
        julia_df['date'] = pd.to_datetime(julia_df['date']).dt.strftime('%Y-%m-%d')
        
        julia_df.to_csv(self.temp_input, index=False)
        print(f"Data prepared and saved to {self.temp_input}")

    def run_julia(self):
        """Executes the Julia script via subprocess."""
        print("Running Julia VitELO calculations...")
        try:
            # We call julia and pass the script and the temp file as an argument
            result = subprocess.run(
                [self.julia_path, self.script_path, self.temp_input],
                capture_output=True,
                text=True,
                check=True
            )
            print("Julia Output:", result.stdout)
            return True
        except subprocess.CalledProcessError as e:
            print("Error running Julia:", e.stderr)
            return False

    def get_results(self):
        """Reads the output generated by Julia back into Python."""
        if os.path.exists(self.temp_output):
            return pd.read_csv(self.temp_output)
        else:
            print("Output file not found. Check if Julia script ran correctly.")
            return None

# Example usage within your existing pipeline:
# wrapper = VitELOWrapper()
# wrapper.prepare_data(main_match_df)
# if wrapper.run_julia():
#     vitelo_results = wrapper.get_results()